### ISSUE TITLE
Quoi faire si une ligne a plusieurs liens ?

### ISSUE THREAD

**Issue by restuccia** [etalab/suivi-ouverture#17]
E.g. pour "Données sur les contaminants chimiques marins et les données du contrôle sanitaire des eaux potables disponibles par API via Hub'eau" on a deux liens vers deux APIs différentes.

**Comment by taniki** [comment]
Deux lignes dans l'airtable, une "Hub'Eau - Indicateurs Eau potable et Assainissement" et une autre "Hub'Eau - Surveillance du littoral" ou quelque chose dans ce goût là quoi :)

**Comment by taniki** [comment]
- Données sur les contaminants chimiques marins
- Données du contrôle sanitaire des eaux potables disponibles
