### ISSUE TITLE
Improve filter deselect

### ISSUE THREAD

**Issue by restuccia** [etalab/suivi-ouverture#18]
La manière actuelle de désélectionner un filtre n'est pas très intuitive.
Peut-on envisager une manière plus simple ? E.g. un bouton « Réinitialiser les filtres » ?

**Comment by taniki** [comment]
yes, c'est ce que je pensais faire au départ. Il y a aussi l'option https://vue-select.org/ mais j'étais pas sûr d'avoir un rendu dsfr facile avec.

**Comment by taniki** [comment]
petite rustine. ça mériterait de refaire un petit tour de design sur cet élément d'interface qui ré-apparait sur d'autres produits

**Comment by restuccia** [comment]
Ohhh c'est cool vue-select, il faudra faire une issue sur dsfr pour demander le composant !
En tout cas merci beaucoup, je crois que ça fera l'affaire pour le moment :)
